# Site settings
description: Daiva Nudi :: Tulu Nadu
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://daivanudi.dharmasthana.in" # the base hostname & protocol for your site 
title: ದೈವ ನುಡಿ | ಧರ್ಮಸ್ಥಾನ
# User settings
username: ದೈವ ನುಡಿ 
user_description: 
user_title: Daiva Nudi
email: anon@anon.com
twitter_username: ashwin_mulky
github_username:  AshwinMulky
gplus_username:  
disqus_username: AshwinMulky

# Build settings
markdown: kramdown
highlighter: pygments
permalink: /:title/


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
